version: 2

defaults:
  - &test_defaults
    docker:
      - image: solita/ubuntu-systemd
      - image: rabbitmq:3.7.4

    steps:
      - checkout
      - run: >
          if [ -n "$CI_PULL_REQUEST" ]; then
            PR_ID=${CI_PULL_REQUEST##*/}
            git fetch origin +refs/pull/$PR_ID/merge:
            git checkout -qf FETCH_HEAD
          fi

      - run: |
          apt-get install -y cron
          curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py

      - run: |
          /etc/init.d/cron start
          pip install -U pip==9.0.1
          pip install tox
          tox -e ${TOX_TEST}

jobs:
  flake8:
    <<: *test_defaults
    environment:
      TOX_TEST: flake8

  docs:
    <<: *test_defaults
    environment:
      TOX_TEST: docs

  py26:
    <<: *test_defaults
    environment:
      TOX_TEST: py26

  py27:
    <<: *test_defaults
    environment:
      TOX_TEST: py27

workflows:
  version: 2

  run_test:
    jobs:
#      - flake8
#      - docs
#      - py26
      - py27