version: 2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

defaults:
  - &test_defaults
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3.7.4

    steps:
      - checkout
      - run:
          name: Install and run cron
          command: sudo apt-get install cron
      - run:
          name: Run cron
          command: sudo /etc/init.d/cron start
      - run:
          name: Install and run tox
          command: |
                   sudo pip install tox
                   python -m tox -e ${TOX_TEST}

  - &test_defaults_for_python26
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3.7.4
    environment:
      PYTHON_VERSION: 2.6.8
    steps:
      - checkout
      - run:
          name: Install and set python version with pyenv
          command: |
                   git clone https://github.com/yyuu/pyenv.git ~/.pyenv
                   export PYENV_ROOT="$HOME/.pyenv"
                   export PATH="$PYENV_ROOT/bin:$PATH"
                   sudo apt-get install -y make build-essential libssl1.0-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
                   pyenv install $PYTHON_VERSION
                   pyenv local $PYTHON_VERSION
      - run:
          name: Install and run cron
          command: sudo apt-get install cron
      - run:
          name: Run cron–
          command: sudo /etc/init.d/cron start
      - run:
          name: Install tox
          command: sudo pip install tox tox-pyenv
      - run:
          name: Run tox of specfic environment
          command: tox -e ${TOX_TEST}

jobs:
  flake8:
    <<: *test_defaults
    environment:
      TOX_TEST: flake8

  docs:
    <<: *test_defaults
    environment:
      TOX_TEST: docs

  py26:
    <<: *test_defaults_for_python26
    environment:
      TOX_TEST: py26

  py27:
    <<: *test_defaults
    environment:
      TOX_TEST: py27

workflows:
  version: 2

  run_test:
    jobs:
      - py27